/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package show;

import admin.Admin;
import admin.AdminTable;
import admin.AdminTableGUI;
import static admin.AdminTableGUI.pass;
import static admin.AdminTableGUI.user;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PiMS
 */
public class EditAdmin extends javax.swing.JFrame {

    private static String aId;
   private Admin admin = new Admin();
    public EditAdmin() {
        initComponents();
        addToTable(AdminTable.AdminTableList());
        adminT.setAutoCreateRowSorter(true);
    }

    
    //เอาข้อมูลจากฐานข้อมูลมาแสดงในรูปแบบของตารางโดยใช้ ArrayList
  DefaultTableModel model = new DefaultTableModel();
    public void addToTable(ArrayList<AdminTable> at){       
        model.setColumnIdentifiers(new Object[]{"USERNAME","PASSWORD","IDADMIN"});
        Object[] row = new Object[3];
        if(at != null){
            for(int i = 0; i < at.size(); i++){
                row[0] = at.get(i).getUsername();
                row[1] = at.get(i).getPassword();
                row[2] = at.get(i).getIdAdmin();               
                model.addRow(row);
            }
        }
       adminT.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBut = new javax.swing.JButton();
        homeBut = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        idBG = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminT = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        user1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(95, 95, 96));
        user.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 440, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        pass.setBackground(new java.awt.Color(95, 95, 96));
        pass.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 440, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, -1, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\up.png")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, 50));

        backBut.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\backBut.png")); // NOI18N
        backBut.setContentAreaFilled(false);
        jPanel1.add(backBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, -1, -1));

        homeBut.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\homeBut.png")); // NOI18N
        homeBut.setContentAreaFilled(false);
        homeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButActionPerformed(evt);
            }
        });
        jPanel1.add(homeBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 10, -1, -1));

        id.setBackground(new java.awt.Color(95, 95, 96));
        id.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 40, 30));

        idBG.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        idBG.setForeground(new java.awt.Color(255, 255, 255));
        idBG.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\id.png")); // NOI18N
        jPanel1.add(idBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 70, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\up.png")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, -1, 50));

        Edit.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\edit.png")); // NOI18N
        Edit.setContentAreaFilled(false);
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, -1, 40));

        delete.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\delete.png")); // NOI18N
        delete.setContentAreaFilled(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 500, -1, 40));

        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\add.png")); // NOI18N
        add.setContentAreaFilled(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 500, -1, 40));

        adminT.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        adminT.setForeground(new java.awt.Color(153, 153, 153));
        adminT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        adminT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adminT);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 560, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\admin\\table.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PiMS\\Desktop\\GUIProject\\uiP\\home\\backgroundAdmin.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        user1.setBackground(new java.awt.Color(95, 95, 96));
        user1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setBorder(null);
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        jPanel1.add(user1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 440, -1));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 440, 30));

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButActionPerformed

    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1ActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
         int index = adminT.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) adminT.getModel();
         String username = user.getText();
         String password = pass.getText();
         String aId = idBG.getText();
   
        adminT.setVisible(true);
        user.setText(username);
        pass.setText(password);
        idBG.setText(aId);
        
       
         
        if(index < 0){ 
            JOptionPane.showMessageDialog(null, "Please select record for Deleting!");
        }else{
            Object[] options = {"Yes", "No"};
            int n = JOptionPane.showOptionDialog(null, "Do you want to EDIT data?", 
           "Confirm to EDIT?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, 
            null, options, options[1]);
            System.out.println("Confirm edit: "+n);
            
             
            if(n == 0){ //ถ้ากดyesเพื่อลบ
                try {
            Admin.editData(username, password,Integer.parseInt(aId));
             } catch (SQLException e) {
            System.err.println(e.getMessage());
             }
            }
        }
       
        adminT.setVisible(false);
        this.setVisible(false);
        new EditAdmin().setVisible(true);
    }//GEN-LAST:event_EditActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int index = adminT.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) adminT.getModel();
         String username = (String) model.getValueAt(index, 0).toString();
         String password = (String) model.getValueAt(index, 1).toString();
         String aId = model.getValueAt(index, 2).toString();
       
        adminT.setVisible(true);
        user.setText(username);
        pass.setText(password);
        idBG.setText(aId);
         
        if(index < 0){ 
            JOptionPane.showMessageDialog(null, "Please select record for Deleting!");
        }else{
            Object[] options = {"Yes", "No"};
            int n = JOptionPane.showOptionDialog(null, "Do you want to DELETE data?", 
           "Confirm to DELETE?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, 
            null, options, options[1]);
           
            if(n == 0){ 
                try {
                    int id = Integer.parseInt(aId);
                    Admin.deleteData(id);
               
                    this.setVisible(false);
                    new EditAdmin().setVisible(true);
                } catch (Exception e) {
                   System.err.println(e.getMessage());
                }
            }
        }
       
        adminT.setVisible(false);
        this.setVisible(false);
        new EditAdmin().setVisible(true);
                                           

    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
       adminT.setVisible(false); 
        new EditAdmin().setVisible(true);
        
        int index = adminT.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) adminT.getModel();
         String username = user.getText();
         String password = pass.getText();
   
        adminT.setVisible(true);
        user.setText(username);
        pass.setText(password);
        idBG.setText(aId);
        
       
         
        if(index < 0){ 
            JOptionPane.showMessageDialog(null, "Please select record for Deleting!");
        }else{
            Object[] options = {"Yes", "No"};
            int n = JOptionPane.showOptionDialog(null, "Do you want to INSERT data?", 
           "Confirm to INSERT?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, 
            null, options, options[1]);
            System.out.println("Confirm edit: "+n);
            
             
            if(n == 0){ //ถ้ากดyesเพื่อลบ
                 try {
                Admin.insertAdmin(username,password); 
            
                } catch (SQLException e) {
                System.err.println(e.getMessage());
                }
            }
        }
       
        adminT.setVisible(false);
        this.setVisible(false);
        new EditAdmin().setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void adminTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTMouseClicked
        int index = adminT.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel) adminT.getModel();
         String username = (String) model.getValueAt(index, 0).toString();
         String password = (String) model.getValueAt(index, 1).toString();
         String id = model.getValueAt(index, 2).toString();
       
        
        adminT.setVisible(true);
        user.setText(username);
        pass.setText(password);
        idBG.setText(id);
       
    }//GEN-LAST:event_adminTMouseClicked

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JButton add;
    private javax.swing.JTable adminT;
    private javax.swing.JButton backBut;
    private javax.swing.JButton delete;
    private javax.swing.JButton homeBut;
    private javax.swing.JTextField id;
    private javax.swing.JLabel idBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    private javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
